#pragma once
#include "includes.h"
#include <cstdio>
#include <cstring>
#include <vector>

// ─────────────────────────────────────────────────────────────────────────────
// Tiny Wavefront-OBJ loader for the impossible-figure project.
//
//  - Parses `v x y z` (vertices) and `vn x y z` (normals).
//  - Parses `f a//na b//nb c//nc d//nd` quads OR triangles.
//  - Triangulates quads into two triangles (a,b,c) + (a,c,d).
//  - Output is two parallel std::vectors that match the project's existing
//    `glDrawArrays(GL_TRIANGLES, ...)` flow: positions and colors per vertex.
//  - Per-face colors are assigned from the OBJ-provided face normal so that
//    +X/-X, +Y/-Y, +Z/-Z faces all get different shades (matches the look of
//    the existing hand-built shapes).
//
// CRITICAL: vertices are NOT welded. The mescher figures (and any figure
// generated by the Paradox bisect tool) rely on shared 2D positions having
// DIFFERENT z values across adjacent faces. Welding would break the illusion.
// This loader naturally avoids welding by emitting one vertex per face-corner.
// ─────────────────────────────────────────────────────────────────────────────

struct ObjColorPalette {
    vec4 xp, xn;  // +X face, -X face
    vec4 yp, yn;  // +Y face, -Y face
    vec4 zp, zn;  // +Z face, -Z face
    vec4 generic; // fallback for off-axis normals
};

// Pick the closest cardinal face color for a given normal.
inline vec4 obj_color_for_normal(const vec3& n, const ObjColorPalette& p)
{
    float ax = fabsf(n.x), ay = fabsf(n.y), az = fabsf(n.z);
    float maxc = ax > ay ? ax : ay;
    if (az > maxc) maxc = az;
    // If the normal is clearly aligned with one axis (>80% along it) pick that face.
    if (maxc < 0.8f) return p.generic;
    if (ax == maxc) return n.x >= 0 ? p.xp : p.xn;
    if (ay == maxc) return n.y >= 0 ? p.yp : p.yn;
    return n.z >= 0 ? p.zp : p.zn;
}

// Returns true on success. Triangulates quad faces.
inline bool obj_load(const char* path,
                     const ObjColorPalette& palette,
                     std::vector<vec4>& out_positions,
                     std::vector<vec4>& out_colors)
{
    FILE* f = fopen(path, "r");
    if (!f) { fprintf(stderr, "obj_load: cannot open %s\n", path); return false; }

    std::vector<vec3> verts;
    std::vector<vec3> norms;
    out_positions.clear();
    out_colors.clear();

    char line[1024];
    while (fgets(line, sizeof(line), f))
    {
        if (line[0] == '#' || line[0] == 'o' || line[0] == '\n' || line[0] == '\0') continue;
        if (line[0] == 'v' && line[1] == ' ')
        {
            float x, y, z;
            if (sscanf(line + 2, "%f %f %f", &x, &y, &z) == 3) verts.push_back(vec3(x, y, z));
        }
        else if (line[0] == 'v' && line[1] == 'n' && line[2] == ' ')
        {
            float x, y, z;
            if (sscanf(line + 3, "%f %f %f", &x, &y, &z) == 3) norms.push_back(vec3(x, y, z));
        }
        else if (line[0] == 'f' && line[1] == ' ')
        {
            // Parse up to 4 vertex-indices on the face line.
            int vi[4] = {0,0,0,0};
            int ni[4] = {0,0,0,0};
            int count = 0;
            const char* p = line + 2;
            while (*p && count < 4)
            {
                while (*p == ' ' || *p == '\t') p++;
                if (!*p || *p == '\n') break;
                int v_idx = 0, n_idx = 0, t_idx = 0;
                // Try the three formats: v//n, v/t/n, v
                int read = 0;
                if (sscanf(p, "%d//%d%n", &v_idx, &n_idx, &read) >= 2) {
                    // matched v//n
                } else if (sscanf(p, "%d/%d/%d%n", &v_idx, &t_idx, &n_idx, &read) >= 3) {
                    // matched v/t/n
                } else if (sscanf(p, "%d%n", &v_idx, &read) >= 1) {
                    // matched v only
                } else {
                    break;
                }
                vi[count] = v_idx;
                ni[count] = n_idx;
                count++;
                p += read;
            }
            if (count < 3) continue;

            // Use the per-face normal (first vertex's normal) to pick a color
            vec3 face_n(0, 0, 1);
            if (ni[0] > 0 && ni[0] <= (int)norms.size()) face_n = norms[ni[0] - 1];
            else if (count >= 3) {
                // No normals provided — compute from first triangle
                vec3 a = verts[vi[0] - 1];
                vec3 b = verts[vi[1] - 1];
                vec3 c = verts[vi[2] - 1];
                face_n = normalize(cross(b - a, c - a));
            }
            vec4 face_c = obj_color_for_normal(face_n, palette);

            auto emit_tri = [&](int i0, int i1, int i2)
            {
                for (int idx : {i0, i1, i2})
                {
                    const vec3& v = verts[vi[idx] - 1];
                    out_positions.push_back(vec4(v.x, v.y, v.z, 1.0f));
                    out_colors.push_back(face_c);
                }
            };

            // Fan triangulation (works for tris, quads, and n-gons)
            for (int i = 1; i + 1 < count; i++)
                emit_tri(0, i, i + 1);
        }
    }
    fclose(f);

    if (out_positions.empty())
    {
        fprintf(stderr, "obj_load: %s loaded zero vertices\n", path);
        return false;
    }
    fprintf(stderr, "obj_load: %s -> %zu verts (%zu raw verts, %zu normals)\n",
            path, out_positions.size(), verts.size(), norms.size());
    return true;
}
