#include "background.h"
#include "obj_shape.h"

// ─────────────────────────────────────────────────────────────────────────────
// Penrose Triangle — CONTINUOUS variant from the Blender Paradox Toolkit.
//
// Mirrors the setup of slot #3 (Blocked Penrose) exactly, just with a
// different OBJ and a cool palette so the pair reads as smooth vs blocky.
//
// Generated by:  bpy.ops.object.paradox_construct_penrose_triangle(block_checkbox=False)
// Exported to:   models/penrose_triangle.obj
// ─────────────────────────────────────────────────────────────────────────────

static ObjShape g_shape;

// Cool slate-blue palette — distinct from slot #3's warm orange/clay.
static ObjColorPalette continuous_palette()
{
    ObjColorPalette p;
    p.xp = vec4(0.62f, 0.72f, 0.88f, 1.0f);  // X+ — pale slate
    p.xn = vec4(0.46f, 0.56f, 0.72f, 1.0f);  // X-
    p.yp = vec4(0.74f, 0.82f, 0.92f, 1.0f);  // Y+ — light sky
    p.yn = vec4(0.52f, 0.62f, 0.78f, 1.0f);  // Y-
    p.zp = vec4(0.68f, 0.74f, 0.82f, 1.0f);  // Z+ — silver-blue
    p.zn = vec4(0.50f, 0.58f, 0.70f, 1.0f);  // Z-
    p.generic = vec4(0.58f, 0.66f, 0.78f, 1.0f);
    return p;
}

void penrose_init()
{
    g_shape.init("../models/penrose_triangle.obj", continuous_palette());

    // Penrose Triangle bar layout (from the actual OBJ mesh):
    //   Z-bar at (x=5, y=0, z=-6..+6)         long, along Z axis
    //   X-bar at (x=-6..+6, y=0, z=-5)        long, along X axis
    //   Y-bar 1 at (x=5,  y=1..5,  z=5)       short, along Y axis (closes top corner)
    //   Y-bar 2 at (x=-5, y=-5..-1, z=-5)     short, along Y axis (closes bottom corner)
    //
    // The figure is "impossible": the loop closes via a 3D JUMP from
    // (-5,-5,-5) → (5,5,5) — both world points project to iso (0, 0), so
    // the jump is invisible at the magic angle.
    //
    // Path traverses the loop in 5 segments:
    //   A → B   Y-bar 1     (5,5,5) → (5,0,5)
    //   B → C   Z-bar       (5,0,5) → (5,0,-5)
    //   C → D   X-bar       (5,0,-5) → (-5,0,-5)
    //   D → E   Y-bar 2     (-5,0,-5) → (-5,-5,-5)
    //   E → A   impossible  (-5,-5,-5) → (5,5,5)  (invisible at iso angle)
    //
    // Each segment's "up" is the iso-axis component perpendicular to the
    // bar axis — that's the face visible to the iso camera, so the ball
    // rests on the bar's outward-facing edge.
    g_shape.setBallPath({
        { vec3( 5.0f,  5.0f,  5.0f), vec3(1.0f, 0.0f, 1.0f) },  // A: Y-bar 1 up (perp to Y)
        { vec3( 5.0f,  0.0f,  5.0f), vec3(1.0f, 1.0f, 0.0f) },  // B: Z-bar up (perp to Z)
        { vec3( 5.0f,  0.0f, -5.0f), vec3(0.0f, 1.0f, 1.0f) },  // C: X-bar up (perp to X)
        { vec3(-5.0f,  0.0f, -5.0f), vec3(1.0f, 0.0f, 1.0f) },  // D: Y-bar 2 up
        { vec3(-5.0f, -5.0f, -5.0f), vec3(1.0f, -1.0f, 0.0f) }, // E: impossible-jump up (any perp to iso)
    }, /*thickness=*/1.0f, /*ballRadius=*/0.45f);

    // Initialize lattice background
    bg_init_lattice();
}
void penrose_display()
{
    // Begin background rendering
    bg_begin_scene();

    // Get camera info and draw lattice background FIRST (so it appears behind)
    double now = glfwGetTime();
    vec3 eye = g_shape.cameraEye;
    vec3 at(0.0f, 0.0f, 0.0f);
    vec3 cam_forward = normalize(eye - at);
    vec3 cam_right = normalize(cross(vec3(0, 1, 0), cam_forward));
    vec3 cam_up = normalize(cross(cam_forward, cam_right));
    float view_size = 9.5f;

    bg_draw_lattice(eye, cam_right, cam_up, cam_forward, view_size, (float)now);

    // Render the penrose triangle on top
    g_shape.display();

    // End background rendering (applies bloom and outputs to screen)
    bg_end_scene();
}
void penrose_mouseButtonCallback(GLFWwindow* w, int b, int a, int) { g_shape.mouseButton(w, b, a); }
void penrose_cursorPosCallback(GLFWwindow*, double x, double y) { g_shape.cursorPos(x, y); }
void penrose_scrollCallback(GLFWwindow*, double, double y) { g_shape.scroll(y); }
void penrose_keyCallback(GLFWwindow* w, int k, int, int a, int) { g_shape.key(w, k, a); }
