#include "obj_shape.h"

// ─────────────────────────────────────────────────────────────────────────────
// Penrose Triangle — CONTINUOUS variant from the Blender Paradox Toolkit.
//
// Mirrors the setup of slot #3 (Blocked Penrose) exactly, just with a
// different OBJ and a cool palette so the pair reads as smooth vs blocky.
//
// Generated by:  bpy.ops.object.paradox_construct_penrose_triangle(block_checkbox=False)
// Exported to:   models/penrose_triangle.obj
// ─────────────────────────────────────────────────────────────────────────────

static ObjShape g_shape;

// Cool slate-blue palette — distinct from slot #3's warm orange/clay.
static ObjColorPalette continuous_palette()
{
    ObjColorPalette p;
    p.xp = vec4(0.62f, 0.72f, 0.88f, 1.0f);   // X+ — pale slate
    p.xn = vec4(0.46f, 0.56f, 0.72f, 1.0f);   // X-
    p.yp = vec4(0.74f, 0.82f, 0.92f, 1.0f);   // Y+ — light sky
    p.yn = vec4(0.52f, 0.62f, 0.78f, 1.0f);   // Y-
    p.zp = vec4(0.68f, 0.74f, 0.82f, 1.0f);   // Z+ — silver-blue
    p.zn = vec4(0.50f, 0.58f, 0.70f, 1.0f);   // Z-
    p.generic = vec4(0.58f, 0.66f, 0.78f, 1.0f);
    return p;
}

void penrose_init()
{
    g_shape.init("../models/penrose_triangle.obj", continuous_palette());

    // Penrose Triangle bar layout (from the actual OBJ mesh):
    //   Z-bar at (x=5, y=0, z=-6..+6)         long, along Z axis
    //   X-bar at (x=-6..+6, y=0, z=-5)        long, along X axis
    //   Y-bar 1 at (x=5,  y=1..5,  z=5)       short, along Y axis (closes top corner)
    //   Y-bar 2 at (x=-5, y=-5..-1, z=-5)     short, along Y axis (closes bottom corner)
    //
    // The figure is "impossible": the loop closes via a 3D JUMP from
    // (-5,-5,-5) → (5,5,5) — both world points project to iso (0, 0), so
    // the jump is invisible at the magic angle.
    //
    // Path traverses the outer surface of the impossible loop:
    //   P_mid_front -> P_top        Y-bar 1 (upper half of vertical bar)
    //   P_top -> P_left             Z-bar (left diagonal bar)
    //   P_left -> P_bottom          X-bar (bottom diagonal bar)
    //   P_bottom -> P_mid_back      Y-bar 2 (lower half of vertical bar)
    //   P_mid_back -> P_mid_front   impossible teleport jump (invisible, both project to screen (0, 0.668))
    g_shape.setBallPath({
        { vec3( 5.818f,  5.818f,  5.818f), vec3(0.0f, 0.0f, 0.0f) }, // Front bar center (P_mid_front)
        { vec3( 5.818f,  0.0f,    5.818f), vec3(0.0f, 0.0f, 0.0f) }, // Top corner (P_top)
        { vec3( 5.818f,  0.0f,   -5.818f), vec3(0.0f, 0.0f, 0.0f) }, // Left corner (P_left)
        { vec3(-5.818f,  0.0f,   -5.818f), vec3(0.0f, 0.0f, 0.0f) }, // Bottom corner (P_bottom)
        { vec3(-5.818f, -5.818f, -5.818f), vec3(0.0f, 0.0f, 0.0f) }, // Back bar center (P_mid_back)
    }, /*thickness=*/0.0f, /*ballRadius=*/0.45f);
}
void penrose_display() { g_shape.display(); }
void penrose_mouseButtonCallback(GLFWwindow* w, int b, int a, int) { g_shape.mouseButton(w, b, a); }
void penrose_cursorPosCallback(GLFWwindow*, double x, double y) { g_shape.cursorPos(x, y); }
void penrose_scrollCallback(GLFWwindow*, double, double y) { g_shape.scroll(y); }
void penrose_keyCallback(GLFWwindow* w, int k, int, int a, int) { g_shape.key(w, k, a); }
