#include "obj_shape.h"

// ─────────────────────────────────────────────────────────────────────────────
// Penrose Triangle — CONTINUOUS variant from the Blender Paradox Toolkit.
//
// Mirrors the setup of slot #3 (Blocked Penrose) exactly, just with a
// different OBJ and a cool palette so the pair reads as smooth vs blocky.
//
// Generated by:  bpy.ops.object.paradox_construct_penrose_triangle(block_checkbox=False)
// Exported to:   models/penrose_triangle.obj
// ─────────────────────────────────────────────────────────────────────────────

static ObjShape g_shape;

// ── Cyber Grid Background (fades in when finished) ──────────────────────────
static GLuint  bg_program    = 0;
static GLuint  bg_vao        = 0;
static GLuint  bg_vbo        = 0;
static GLint   bg_baseLoc    = -1;
static GLint   bg_timeLoc    = -1;
static GLint   bg_amountLoc  = -1;

static void bg_init()
{
    // Reuses the fullscreen quad vertex shader with our new cyber grid fragment shader
    bg_program = InitShader("../shaders/core/vshader_halo.glsl",
                            "../shaders/backgrounds/fshader_cyber_grid.glsl");
    bg_baseLoc   = glGetUniformLocation(bg_program, "uBaseColor");
    bg_timeLoc   = glGetUniformLocation(bg_program, "uTime");
    bg_amountLoc = glGetUniformLocation(bg_program, "uAmount");

    // Fullscreen triangle strip — 4 NDC corners.
    static const float quad[] = {
        -1.0f, -1.0f,
         1.0f, -1.0f,
        -1.0f,  1.0f,
         1.0f,  1.0f,
    };
    glGenVertexArrays(1, &bg_vao);
    glBindVertexArray(bg_vao);
    glGenBuffers(1, &bg_vbo);
    glBindBuffer(GL_ARRAY_BUFFER, bg_vbo);
    glBufferData(GL_ARRAY_BUFFER, sizeof(quad), quad, GL_STATIC_DRAW);
    GLint aPos = glGetAttribLocation(bg_program, "aPos");
    if (aPos >= 0)
    {
        glEnableVertexAttribArray(aPos);
        glVertexAttribPointer(aPos, 2, GL_FLOAT, GL_FALSE, 0, (GLvoid*)0);
    }
    glBindVertexArray(0);
}

// Chrome steel palette — near-white with cool blue tint, high contrast between faces
// so the metallic shader's environment reflections read clearly on each bar.
static ObjColorPalette continuous_palette()
{
    ObjColorPalette p;
    p.xp = vec4(0.82f, 0.85f, 0.90f, 1.0f);  // X+ bright face
    p.xn = vec4(0.48f, 0.52f, 0.58f, 1.0f);  // X- darker
    p.yp = vec4(0.88f, 0.91f, 0.95f, 1.0f);  // Y+ lightest
    p.yn = vec4(0.42f, 0.46f, 0.54f, 1.0f);  // Y- deepest shadow
    p.zp = vec4(0.72f, 0.76f, 0.83f, 1.0f);  // Z+ mid
    p.zn = vec4(0.38f, 0.42f, 0.50f, 1.0f);  // Z- darkest
    p.generic = vec4(0.65f, 0.68f, 0.75f, 1.0f);
    return p;
}

void penrose_init()
{
    g_shape.init("../models/penrose_triangle.obj", continuous_palette(), nullptr, "../shaders/objects/fshader_penrose_cyber.glsl");

    // Penrose Triangle bar layout (from the actual OBJ mesh):
    //   Z-bar at (x=5, y=0, z=-6..+6)         long, along Z axis
    //   X-bar at (x=-6..+6, y=0, z=-5)        long, along X axis
    //   Y-bar 1 at (x=5,  y=1..5,  z=5)       short, along Y axis (closes top corner)
    //   Y-bar 2 at (x=-5, y=-5..-1, z=-5)     short, along Y axis (closes bottom corner)
    //
    // The figure is "impossible": the loop closes via a 3D JUMP from
    // (-5,-5,-5) → (5,5,5) — both world points project to iso (0, 0), so
    // the jump is invisible at the magic angle.
    //
    // Path traverses the outer surface of the impossible loop:
    //   P_mid_front -> P_top        Y-bar 1 (upper half of vertical bar)
    //   P_top -> P_left             Z-bar (left diagonal bar)
    //   P_left -> P_bottom          X-bar (bottom diagonal bar)
    //   P_bottom -> P_mid_back      Y-bar 2 (lower half of vertical bar)
    //   P_mid_back -> P_mid_front   impossible teleport jump (invisible, both project to screen (0, 0.668))
    g_shape.setBallPath(
        {
            {vec3(5.818f, 5.818f, 5.818f), vec3(0.0f, 0.0f, 0.0f)},     // Front bar center (P_mid_front)
            {vec3(5.818f, 0.0f, 5.818f), vec3(0.0f, 0.0f, 0.0f)},       // Top corner (P_top)
            {vec3(5.818f, 0.0f, -5.818f), vec3(0.0f, 0.0f, 0.0f)},      // Left corner (P_left)
            {vec3(-5.818f, 0.0f, -5.818f), vec3(0.0f, 0.0f, 0.0f)},     // Bottom corner (P_bottom)
            {vec3(-5.818f, -5.818f, -5.818f), vec3(0.0f, 0.0f, 0.0f)},  // Back bar center (P_mid_back)
        },
        /*thickness=*/0.0f, /*ballRadius=*/0.32f);
    g_shape.useMirrorBall(5);   // 5 = iridescent/rainbow style
    g_shape.setMetallic(true);  // chrome PBR with ball reflection
    g_shape.ballStartS = 0.12f; // start closer to the top corner on the front bar

    bg_init();
}
void penrose_display()
{
    constexpr float REVEAL_DELAY = 0.5f;
    constexpr float REVEAL_TRACE = 5.0f;
    float revealT = g_shape.postSolveTime - REVEAL_DELAY;
    if (revealT < 0.0f) revealT = 0.0f;
    float amount = revealT / REVEAL_TRACE;
    if (amount > 1.0f) amount = 1.0f;

    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

    // Render the holographic cyber grid background (fades in as amount increases)
    if (bg_program != 0)
    {
        glUseProgram(bg_program);
        glUniform3f(bg_baseLoc,   0.75f, 0.78f, 0.80f);   // pale slate base
        glUniform1f(bg_timeLoc,   (float)glfwGetTime());
        glUniform1f(bg_amountLoc, amount);
        glBindVertexArray(bg_vao);
        glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);
        glBindVertexArray(0);
    }

    g_shape.display();
}
void penrose_mouseButtonCallback(GLFWwindow* w, int b, int a, int) { g_shape.mouseButton(w, b, a); }
void penrose_cursorPosCallback(GLFWwindow*, double x, double y) { g_shape.cursorPos(x, y); }
void penrose_scrollCallback(GLFWwindow*, double, double y) { g_shape.scroll(y); }
void penrose_keyCallback(GLFWwindow* w, int k, int, int a, int) { g_shape.key(w, k, a); }
