#include "obj_shape.h"

// ─────────────────────────────────────────────────────────────────────────────
// Blocked Penrose — now loaded from the Blender Paradox Toolkit's BLOCK-VARIANT
// of the Penrose Triangle.
//
// Replaces the previous procedural 13-cube chain. The OBJ is generated by
// calling `bpy.ops.object.paradox_construct_penrose_triangle(block_checkbox=True)`
// in Blender and exporting the result. The visual idea is the same (a chain of
// discrete blocks instead of continuous bars) but the geometry, illusion joint
// and corner blending all come from the Paradox addon — same engine that makes
// the smooth Penrose Triangle in slot #2.
//
// Function names keep the `pbp_` prefix so main.cpp's dispatch is unchanged.
// ─────────────────────────────────────────────────────────────────────────────

static ObjShape g_shape;

// Distinct palette from the smooth Penrose Triangle so the two are easy to
// tell apart side-by-side. Warmer, more saturated tones.
static ObjColorPalette blocks_palette()
{
    ObjColorPalette p;
    p.xp = vec4(0.78f, 0.56f, 0.48f, 1.0f);   // X+ — warm orange
    p.xn = vec4(0.62f, 0.42f, 0.36f, 1.0f);   // X-
    p.yp = vec4(0.86f, 0.74f, 0.52f, 1.0f);   // Y+ — straw
    p.yn = vec4(0.70f, 0.58f, 0.40f, 1.0f);   // Y-
    p.zp = vec4(0.72f, 0.60f, 0.52f, 1.0f);   // Z+ — clay
    p.zn = vec4(0.56f, 0.46f, 0.40f, 1.0f);   // Z-
    p.generic = vec4(0.65f, 0.55f, 0.48f, 1.0f);
    return p;
}

void pbp_init()
{
    g_shape.init("../models/penrose_blocks.obj", blocks_palette());

    // The mesh itself has been rotated 60° around the iso axis (1,1,1) when
    // exported from Blender — that axis is parallel to the bisect-cut normals,
    // so the illusion still works at S=(0,0,0) but the figure shows spun 60°
    // in the screen plane relative to slot 2. Keep ObjShape's default R pose.

    // No ball orbit on this slot — only slots 1 (procedural polygon) and
    // 2 (Penrose Triangle) keep their rolling indicator.
}
void pbp_display()
{
    g_shape.display();
}
void pbp_mouseButtonCallback(GLFWwindow* w, int b, int a, int) { g_shape.mouseButton(w, b, a); }
void pbp_cursorPosCallback(GLFWwindow*, double x, double y) { g_shape.cursorPos(x, y); }
void pbp_scrollCallback(GLFWwindow*, double, double y) { g_shape.scroll(y); }
void pbp_keyCallback(GLFWwindow* w, int k, int, int a, int) { g_shape.key(w, k, a); }
